### PR TITLE
Change to a relevant card when crew member clicks on a notification

### PR DESCRIPTION
**Pull request by ericman314**
## Description
- Added a `relevantCards` property to the `Notification` type, which is an array of strings indicating the component name of the card or cards that would be relevant to the notification, in order of preference.
- Changed `Alerts.js` so that when a user clicks on a notification, a `cardChangeRequest` for the relevant cards is published.
- Changed `Cards.js` to subscribe to `cardChangeRequest`. When a request is received, it finds a matching card on the station and changes to it.
- Added relevant cards for sensor scan results, etc.

## Additional work needed

Not ready to merge yet. Work is still in progress. Just looking for feedback to see if this is going in the right direction. If so, here is what's left to be done:

- [ ] Add support for opening relevant widgets as well
- [ ] Add relevant cards (or widgets) for all other kinds of notifications
- [ ] Training or some other visual cue that you can click on a notification to switch cards

## Related Issue

#1559

- [ ] I submitted a pull request or created an issue for documenting this feature on the [Thorium Docs](https://github.com/Thorium-Sim/thorium-docs) repo. (Include the issue or pull request url below.)

### CODE REVIEW

**Comment by alexanderson1993** [comment]
Looks perfect so far. 👍

**Comment by alexanderson1993** [comment]
Any updates to this?

**Comment by ericman314** [comment]
Sorry, I've been busy at work the last couple weeks. I'm planning on finishing the remaining notification types soon. If I don't get to it in the next few days, I'll definitely be able to get to after the new year.

**Comment by ericman314** [comment]
I just rebased my local working branch, and all these other commits showed up. Should I just close this PR and submit another one once I'm finished?

**Pull request closed without merging**
